fix comm field in /proc/pid/stat
dtrugman/pfs pull request #34
Opened 2023-11-08 03:34 UTC by joeyshao-wbyt

Although in man page:
    https://man7.org/linux/man-pages/man5/proc.5.html
The comm field has a description: `Strings longer than TASK_COMM_LEN (16) characters (including the terminating null byte) are silently truncated.` However, if you check the kernel code in fs/proc/array.c,(https://elixir.bootlin.com/linux/v6.4.1/source/fs/proc/array.c#L99) you will find that the description is only valid in the `__get_task_comm(tcomm, sizeof(tcomm), p);` branch of `proc_task_name` function. The actual maximum length is 64 instead. Hence, we are seeing pfs isn't reflecting all the `/proc/pid/stat` comm field correctly. Hence the change and the added tests.

2023-11-08 03:35 UTC, joeyshao-wbyt commented
Hi @dtrugman, when you have time, would you mind taking a look for the PR? Please let me know if you have any question about the PR. Thanks!

2023-11-09 23:05 UTC, dtrugman requested changes
Thank you very much for the contribution! Have a few small requests regarding the test utility, but overall it's of great help!

2023-11-09 23:05 UTC, dtrugman commented on test/test_utils.hpp
> +            perror("mkdtemp");
Instead of using the `is_valid`, the convention in this entire project is to throw exceptions when something goes wrong. Can we just raise an `std::runtime_error` here? This way, we also don't need the `REQUIRE` in the tests.

2023-11-09 23:05 UTC, dtrugman commented on test/test_utils.hpp
> +class temp_sandbox_dir
Maybe just `temp_dir`?

2023-11-09 23:05 UTC, dtrugman commented on test/test_utils.hpp
> +        char temp_dir[] = "/tmp/temp_dir_XXXXXX";
Maybe `/tmp/pfs_test_XXXXXX` so its easier to track?

2023-11-09 23:05 UTC, dtrugman commented on test/test_utils.hpp
> +            perror((std::string{"create folder "} + dir + " fail.").c_str());
Can we throw an exception instead?

2023-11-09 23:05 UTC, dtrugman commented on test/test_utils.hpp
> +            perror(
Can we throw an exception instead?

2023-11-09 23:05 UTC, dtrugman commented on test/test_utils.hpp
> +        if (!_sandbox_root.empty())
Check is no longer required if you throw exceptions

2023-11-09 23:05 UTC, dtrugman commented on test/task_stat.cpp
> +TEST_CASE("Parse task stat", "[task][stat]")
Thanks for adding this! I didn't realise we didn't have this test before!

2023-11-10 02:02 UTC, joeyshao-wbyt commented
The comments sound good to me. I will submit patches to address them once it's approved on our side. Thanks!

2023-11-13 00:59 UTC, joeyshao-wbyt commented
Updated with all the comments, thanks!

2023-11-13 19:38 UTC, dtrugman approved these changes

2023-11-13 19:38 UTC, merged

2023-11-13 23:53 UTC, joeyshao-wbyt commented
Thanks!!