fix(package.xml): install ROS package xml file
dtrugman/pfs pull request #50
Opened 2024-12-24 07:57 UTC by reinzor

Required follow up of #47 so that the package can be used from an install space.

2024-12-24 07:57 UTC, reinzor commented
@Rayman FYI

2024-12-24 08:05 UTC, reinzor commented
An alternative would be to `vendor` this package instead of adding ros2 requirements to a vanilla cmake project. Example https://github.com/ros2/rmw_zenoh/tree/rolling/zenoh_cpp_vendor

2024-12-29 09:53 UTC, dtrugman approved these changes

2024-12-29 09:56 UTC, dtrugman requested changes
(Please `git commit --amend` and force push the change, no need for two commits)
Thanks! Just a minor change before committing.

2024-12-29 09:56 UTC, dtrugman commented on CMakeLists.txt
> +    FILES package.xml
Can you please add
set (pfs_PACKAGE_ROS_XML package.xml)

Next to the other PACKAGE `set()` directives?

2025-01-01 21:00 UTC, dtrugman approved these changes
I'll add the minor change later.

2025-01-01 21:00 UTC, merged